CREATE TABLE blast_2 (
	pid_1			VARCHAR(40) NOT NULL,
	pid_2			VARCHAR(40) NOT NULL,
	qlen			INT(10) UNSIGNED NOT NULL,
	slen			INT(10) UNSIGNED NOT NULL,
	bitscore		DOUBLE UNSIGNED NOT NULL,
	evalue			DOUBLE UNSIGNED NOT NULL,
	pident			DOUBLE UNSIGNED NOT NULL,
	nident			INT(10) UNSIGNED NOT NULL,
	length			INT(10) UNSIGNED NOT NULL,
	qcovs			DOUBLE UNSIGNED NOT NULL,
	qstart			INT(10) UNSIGNED NOT NULL,
	qend			INT(10) UNSIGNED NOT NULL,
	sstart			INT(10) UNSIGNED NOT NULL,
	send			INT(10) UNSIGNED NOT NULL,
	scovs			DOUBLE UNSIGNED NOT NULL,
  PRIMARY KEY (pid_1),
  KEY pid_2 (pid_2)
) ENGINE=InnoDB;


